### ISSUE TITLE
Provide the link to project site

### ISSUE THREAD

**Issue by ChrisTorng** [madskristensen/SolutionExtensions#1]
Will you install an extension without knowing how to use it? So please provide the link to project site, either the one in http://visualstudiogallery.msdn.microsoft.com/ or source code.

**Comment by madskristensen** [comment]
Great idea!!

**Comment by yannduran** [comment]
I was just about to make this same suggestion as well, so +1. 

There are two ways that I can think of that it could work:
1. Make the name of the extension a clickable link to the extension page in the gallery (as @ChrisTorng  suggested)
2. Add a column in the list that is either before the name column, or after it, that contains a button that opens the extension page in the gallery

My personal preference would be for the first option I think. And that would probably be easier to implement as well.

There's no need to link to the source code in the dialog box itself, because if source code is available it'll be able to be found via the GitHub link on the gallery page.
